/**
 * Hive integration — writes grocery list items directly to Hive's Google Sheet.
 * Uses the same Google OAuth token (both apps share the same Google account).
 *
 * Hive Items sheet (A:N):
 * id, title, description, status, owner, due_date, labels, parent_id,
 * created_at, updated_at, completed_at, sort_order, created_by, board_id
 */

const HIVE_SPREADSHEET_ID = import.meta.env.VITE_HIVE_SPREADSHEET_ID || '';
const BASE = 'https://sheets.googleapis.com/v4/spreadsheets';

/** Check if the Hive integration is configured. */
export function isHiveConfigured(): boolean {
  return !!HIVE_SPREADSHEET_ID;
}

/** Generate a Hive-compatible item ID. */
function generateId(): string {
  return `item_${crypto.randomUUID().slice(0, 8)}`;
}

interface HiveItem {
  id: string;
  title: string;
  description: string;
  status: string;
  owner: string;
  due_date: string;
  labels: string;
  parent_id: string;
  created_at: string;
  updated_at: string;
  completed_at: string;
  sort_order: number;
  created_by: string;
  board_id: string;
}

function itemToRow(item: HiveItem): any[] {
  return [
    item.id,
    item.title,
    item.description,
    item.status,
    item.owner,
    item.due_date,
    item.labels,
    item.parent_id,
    item.created_at,
    item.updated_at,
    item.completed_at,
    item.sort_order,
    item.created_by,
    item.board_id,
  ];
}

async function appendHiveRows(values: any[][], token: string): Promise<void> {
  const url = `${BASE}/${HIVE_SPREADSHEET_ID}/values/Items!A:N:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ values }),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Hive API error ${res.status}: ${text}`);
  }
}

export interface ShoppingExportItem {
  name: string;
  quantity: number;
  unit: string;
  recipes: string[];
}

/**
 * Export a shopping list to Hive as a parent task with sub-items.
 * Creates:
 *   1. Parent: "🛒 Grocery Store" with due_date
 *   2. Sub-items: one per ingredient ("{qty} {unit} {name}")
 *
 * @returns The parent item ID.
 */
export async function exportToHive(
  items: ShoppingExportItem[],
  shopDate: string,
  boardId: string,
  token: string,
): Promise<string> {
  const now = new Date().toISOString();
  const parentId = generateId();

  // Build parent item
  const parent: HiveItem = {
    id: parentId,
    title: '🛒 Grocery Store',
    description: `Shopping list for meals through ${shopDate}. Generated by Forage.`,
    status: 'To Do',
    owner: '',
    due_date: shopDate,
    labels: '',
    parent_id: '',
    created_at: now,
    updated_at: now,
    completed_at: '',
    sort_order: 0,
    created_by: 'Forage',
    board_id: boardId,
  };

  // Build sub-items
  const subItems: HiveItem[] = items.map((item, idx) => ({
    id: generateId(),
    title: `${item.quantity} ${item.unit} ${item.name}`,
    description: item.recipes.length > 0 ? `For: ${item.recipes.join(', ')}` : '',
    status: 'To Do',
    owner: '',
    due_date: shopDate,
    labels: '',
    parent_id: parentId,
    created_at: now,
    updated_at: now,
    completed_at: '',
    sort_order: idx + 1,
    created_by: 'Forage',
    board_id: boardId,
  }));

  // Append all rows at once (parent + sub-items)
  const rows = [itemToRow(parent), ...subItems.map(itemToRow)];
  await appendHiveRows(rows, token);

  return parentId;
}

/**
 * Format a shopping list as plain text for copy/paste fallback.
 */
export function formatShoppingListText(items: ShoppingExportItem[], shopDate: string): string {
  const lines = [
    `🛒 Grocery Store — ${shopDate}`,
    '',
    ...items.map(item => {
      const recipeNote = item.recipes.length > 0 ? ` (${item.recipes.join(', ')})` : '';
      return `☐ ${item.quantity} ${item.unit} ${item.name}${recipeNote}`;
    }),
    '',
    'Generated by Forage',
  ];
  return lines.join('\n');
}
